import { DM_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/NavBar";

const dm_sans = DM_Sans({
  subsets: ["latin"],
  variable: "--dm_sans",
  display: "swap",
});
const themysion = localFont({
  src: "./fonts/Themysion.ttf",
  variable: "--themysion",
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dm_sans.variable} ${themysion.variable}`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
